import Head from "next/head";
import Navbar from "/components/Navbar";
import Intro from "/components/Intro";
import ListItem from "/components/ListItem";
import GridItem from "/components/GridItem";
import Footer from "/components/Footer";
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Intro />
      <ListItem />
      <GridItem />
      <Footer />
    </div>
  );
}
