import Head from "next/head";
import Navbar from "/components/Navbar";
import Intro from "/components/Intro";
import ListItem from "/components/ListItem";
import GridItem from "/components/GridItem";
import Footer from "/components/Footer";
import { getAllPosts } from "/lib/api";
export default function Home({ posts }) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Intro />
      <ListItem />
      <div className="grid">
        {posts.map((el) => (
          <GridItem post={el} key={el.title} />
        ))}
      </div>

      <Footer />
    </div>
  );
}

export const getStaticProps = async function () {
  const posts = await getAllPosts();
  return {
    props: {
      posts,
    },
  };
};
